# .github/workflows/build.yml
name: Build GpxPlayerDesktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: 🧰 Grant execute for gradlew (Linux only)
        if: runner.os == 'Linux'
        run: chmod +x ./gradlew

      - name: 🧪 Build project
        run: ./gradlew build

      - name: 📦 Package app
        run: ./gradlew packageReleaseDistributionForCurrentOS

      - name: 📤 Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ runner.os }}
          path: build/compose/binaries
